### ISSUE TITLE
panics when accessing from multiple goroutines

### ISSUE THREAD

**Issue by mschneider** [kvz/logstreamer#5]
I observed this behaviour a few times in production as well as in test.

```
panic: runtime error: slice bounds out of range

goroutine 9 [running]:
bytes.(*Buffer).readSlice(0xc8200603f0, 0x10a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/bytes/buffer.go:382 +0x113
bytes.(*Buffer).ReadString(0xc8200603f0, 0xc82009070a, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/bytes/buffer.go:395 +0x4d
github.com/viorama/chronos/backend/Godeps/_workspace/src/github.com/kvz/logstreamer.(*Logstreamer).OutputLines(0xc820060460, 0x0, 0x0)
    /Users/max/Code/go/src/github.com/viorama/chronos/backend/Godeps/_workspace/src/github.com/kvz/logstreamer/logstreamer.go:95 +0x4b
github.com/viorama/chronos/backend/Godeps/_workspace/src/github.com/kvz/logstreamer.(*Logstreamer).Write(0xc820060460, 0xc820180120, 0x115, 0x120, 0x115, 0x0, 0x0)
    /Users/max/Code/go/src/github.com/viorama/chronos/backend/Godeps/_workspace/src/github.com/kvz/logstreamer/logstreamer.go:71 +0x8c
fmt.Fprintln(0x75eb20, 0xc820060460, 0xc82000ea20, 0x2, 0x2, 0x1, 0x0, 0x0)
```

**Comment by kvz** [comment]
Thanks for reporting! I'm unsure how to reproduce this though..

**Comment by mschneider** [comment]
can we skype / hangout about this one?

**Comment by Acconut** [comment]
As it seems logstreamer is not thread safe. If you are using the same log streamer instance from multiple goroutines, you may get a data race when accessing the bytes.Buffer object.

The solution is to either use a new logstreamer for every goroutine or implement access control using a simple lock such as sync.Mutex.

But if you are using the library in a single-threaded way you should be fine.

**Comment by mschneider** [comment]
ok. i used a new logstreamer for every subprocess (before i would reuse them), so far i could not observe further crashes. thank you :+1:

**Comment by kvz** [comment]
Thanks for stepping in @Acconut :100:
